// <auto-generated />
using BasketElo.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace BasketElo.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BasketEloDbContext))]
    [Migration("20260723191500_MergeScgCodeOnlyIdentity")]
    partial class MergeScgCodeOnlyIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This migration contains only an idempotent data merge; the schema
            // model is unchanged from the preceding migration.
        }
    }
}
